const CartActionTypes = {
	CART_HIDDEN: 'CART_HIDDEN',
	CART_SHOW: 'CART_SHOW',
	ADD_ITEM: 'ADD_ITEM',
	CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
	REMOVE_ITEM: 'REMOVE_ITEM',
};

export default CartActionTypes;
